# Generated by Django 4.1.4 on 2023-01-02 19:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0002_alter_business_image_alter_charity_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_event',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
